#!/bin/sh /etc/rc.common

START=10
STOP=10

start() {
	modprobe mac80211
	insmod uccp420wlan

	# Set default settings to improve performance
	sysctl -w net.core.rmem_default=10485760
	sysctl -w net.core.rmem_max=10485760
	sysctl -w net.core.wmem_default=10485760
	sysctl -w net.core.wmem_max=10485760
	sysctl -w net.ipv4.tcp_wmem=10485760
}

stop() {
	rmmod uccp420wlan
}
