#!/bin/sh /etc/rc.common

START=19
STOP=10

SERVICE_DAEMONIZE=0
SERVICE_WRITE_PID=0

start()
{
	uci set dhcp.@dnsmasq[0].noresolv=1
	SERVERS="$(uci get dhcp.@dnsmasq[0].server)"
	INTERFACES="$(uci get dhcp.@dnsmasq[0].interface)"
	if [ "${SERVERS}" != "127.0.0.1#5353" ]; then
	    echo "adding servers"
	    uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#5353
	fi
	if [ "${INTERFACES}" != "lowpan0 eth0" ]; then
	    echo "adding interfaces"
	    uci add_list dhcp.@dnsmasq[0].interface=lowpan0
	    uci add_list dhcp.@dnsmasq[0].interface=eth0
	fi
	uci commit
	
	grep -q -F 'cache-size=0' /etc/dnsmasq.conf || echo 'cache-size=0' >> /etc/dnsmasq.conf
	grep -q -F 'log-queries=extra' /etc/dnsmasq.conf || echo 'log-queries=extra' >> /etc/dnsmasq.conf
}

stop()
{
	echo "Stop"
}
